package me.timothy.bots.memory;

import java.util.ArrayList;
import java.util.List;

import me.timothy.bots.models.HandledModAction;
import me.timothy.bots.models.MonitoredSubreddit;

/**
 * This class is used by the USLPropagator to describe
 * what actions should be taken as a result of a handled mod action.
 * 
 * This result was generated by only considering one subreddit, but
 * the consequences may be greater depending on how complex the 
 * propagator has become.
 * 
 * Note that the propagate result should only be the result of ONE
 * monitored subreddit and ITS configuration with regard to ONE 
 * action that occurred.
 * 
 * @author Timothy
 */
public class PropagateResult {
	
	/**
	 * Which subreddit was considered when creating this result.
	 * Not null.
	 */
	public final MonitoredSubreddit subreddit;
	
	/**
	 * Which handled mod action was considered when creating this result.
	 * Not null.
	 */
	public final HandledModAction handledModAction;
	
	/**
	 * The list of bans that should take place due to this one.
	 * Not null.
	 */
	public final List<UserBanInformation> bans;
	
	/** 
	 * The list of pms that should be sent to subreddits.
	 * Not null. 
	 */
	public final List<ModmailPMInformation> modmailPMs;
	
	/** 
	 * The list of pms that should be sent to Persons. 
	 * Not null.
	 */
	public final List<UserPMInformation> userPMs;

	/** 
	 * If we can't figure out what to do yet 
	 */
	public final boolean postpone;
	
	/**
	 * @param subreddit subreddit was considered to create this
	 * @param handledModAction action that was considered to create this
	 * @param bans the bans that need to occur because of this
	 * @param modmailPMs the modmail pms that need to occur because of this
	 * @param userPMs the users to pm because of this
	 * @param postpone true if we dont know what to do yet
	 */
	public PropagateResult(MonitoredSubreddit subreddit, HandledModAction handledModAction, List<UserBanInformation> bans,
			List<ModmailPMInformation> modmailPMs, List<UserPMInformation> userPMs, boolean postpone) {
		this.subreddit = subreddit;
		this.handledModAction = handledModAction;
		this.bans = bans;
		this.modmailPMs = modmailPMs;
		this.userPMs = userPMs;
		this.postpone = postpone;
	}

	/**
	 * Create a ban history propagate result that does nothing
	 * 
	 * @param subreddit the subreddit that was considered
	 * @param handledModAction the action that was considered
	 */
	public PropagateResult(MonitoredSubreddit subreddit, HandledModAction handledModAction) {
		this(subreddit, handledModAction, new ArrayList<>(), new ArrayList<>(), new ArrayList<>(), false);
	}

	/**
	 * Create a ban history propagate result that does nothing and postpones
	 * 
	 * @param subreddit the subreddit that was considered
	 * @param handledModAction the action that was considered
	 * @param postpone true if we dont know what to do yet
	 */
	public PropagateResult(MonitoredSubreddit subreddit, HandledModAction handledModAction, boolean postpone) {
		this(subreddit, handledModAction, new ArrayList<>(), new ArrayList<>(), new ArrayList<>(), postpone);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bans == null) ? 0 : bans.hashCode());
		result = prime * result + ((handledModAction == null) ? 0 : handledModAction.hashCode());
		result = prime * result + ((modmailPMs == null) ? 0 : modmailPMs.hashCode());
		result = prime * result + (postpone ? 1231 : 1237);
		result = prime * result + ((subreddit == null) ? 0 : subreddit.hashCode());
		result = prime * result + ((userPMs == null) ? 0 : userPMs.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof PropagateResult))
			return false;
		PropagateResult other = (PropagateResult) obj;
		if (bans == null) {
			if (other.bans != null)
				return false;
		} else if (!bans.equals(other.bans))
			return false;
		if (handledModAction == null) {
			if (other.handledModAction != null)
				return false;
		} else if (!handledModAction.equals(other.handledModAction))
			return false;
		if (modmailPMs == null) {
			if (other.modmailPMs != null)
				return false;
		} else if (!modmailPMs.equals(other.modmailPMs))
			return false;
		if (postpone != other.postpone)
			return false;
		if (subreddit == null) {
			if (other.subreddit != null)
				return false;
		} else if (!subreddit.equals(other.subreddit))
			return false;
		if (userPMs == null) {
			if (other.userPMs != null)
				return false;
		} else if (!userPMs.equals(other.userPMs))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "PropagateResult [subreddit=" + subreddit + ", handledModAction=" + handledModAction + ", bans=" + bans
				+ ", modmailPMs=" + modmailPMs + ", userPMs=" + userPMs + ", postpone=" + postpone + "]";
	}
	
	
}
